### ISSUE TITLE
running Veil.py

### ISSUE THREAD

**Issue by ssinghal409** [ssinghal409/ssinghal409#1]
──(root💀kali)-[/opt/Veil]
└─# ./Veil.py                  
Traceback (most recent call last):
  File "/opt/Veil/./Veil.py", line 98, in <module>
    the_conductor = orchestra.Conductor(args)
  File "/opt/Veil/lib/common/orchestra.py", line 29, in __init__
    self.load_tools(cli_stuff)
  File "/opt/Veil/lib/common/orchestra.py", line 75, in load_tools
    self.imported_tools[name] = module.Tools(
  File "tools/evasion/tool.py", line 39, in __init__
    self.load_payloads(cli_options)
  File "tools/evasion/tool.py", line 248, in load_payloads
    module = helpers.load_module(name)
  File "/opt/Veil/lib/common/helpers.py", line 172, in load_module
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "tools/evasion/payloads/auxiliary/pyinstaller_wrapper.py", line 9, in <module>
    from tools.evasion.evasion_common import encryption
  File "/opt/Veil/tools/evasion/evasion_common/encryption.py", line 8, in <module>
    from Crypto.Cipher import ARC4
ModuleNotFoundError: No module named 'Crypto'

**Comment by ssinghal409** [comment]
also tried to install paython3-crypto but getting an error 
─(root💀kali)-[/home/kali]
└─# apt install python3-crypto                                            100 ⨯
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Package python3-crypto is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'python3-crypto' has no installation candidate
